version: "3"

services:
  sqlite-web:
    build:
      dockerfile: Dockerfile
    image: sqlite-web
    ports:
      - 8080:8080
    volumes:
      - data:/data
    environment:
      SQLITE_DATABASE: mydb.sqlite
    command: "sqlite_web -H 0.0.0.0 -x $SQLITE_DATABASE"

